//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.17379
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTools.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReportTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;Field Name=&quot;[:FieldName:]&quot;&gt;
        ///          &lt;DataField&gt;[:FieldName:]&lt;/DataField&gt;
        ///          &lt;rd:TypeName&gt;[:TypeName:]&lt;/rd:TypeName&gt;
        ///        &lt;/Field&gt;
        ///		과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;TableCell&gt;
        ///                  &lt;ReportItems&gt;
        ///                    &lt;Textbox Name=&quot;[:FieldName:]&quot;&gt;
        ///                      &lt;rd:DefaultName&gt;[:FieldName:]&lt;/rd:DefaultName&gt;
        ///                      &lt;Style&gt;
        ///                        &lt;BorderColor&gt;
        ///                          &lt;Default&gt;DimGray&lt;/Default&gt;
        ///                        &lt;/BorderColor&gt;
        ///                        &lt;BorderStyle&gt;
        ///                          &lt;Default&gt;Solid&lt;/Default&gt;
        ///                        &lt;/BorderStyle&gt;
        ///                        &lt;FontFamily&gt;Gulim&lt;/FontFa[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FieldCell {
            get {
                return ResourceManager.GetString("FieldCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///                   &lt;TableCell&gt;
        ///                  &lt;ReportItems&gt;
        ///                    &lt;Textbox Name=&quot;Header_[:FieldText:]&quot;&gt;
        ///                      &lt;Style&gt;
        ///                        &lt;TextAlign&gt;Center&lt;/TextAlign&gt;
        ///                        &lt;Color&gt;White&lt;/Color&gt;
        ///                        &lt;BackgroundColor&gt;#1c3a70&lt;/BackgroundColor&gt;
        ///                        &lt;BorderColor&gt;
        ///                          &lt;Default&gt;DimGray&lt;/Default&gt;
        ///                        &lt;/BorderColor&gt;
        ///                        &lt;BorderStyle&gt;
        ///                   [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HeaderCell {
            get {
                return ResourceManager.GetString("HeaderCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Report xmlns=&quot;http://schemas.microsoft.com/sqlserver/reporting/2005/01/reportdefinition&quot; xmlns:rd=&quot;http://schemas.microsoft.com/SQLServer/reporting/reportdesigner&quot;&gt;
        ///  &lt;DataSources&gt;
        ///    &lt;DataSource Name=&quot;[:DataSourceName:]&quot;&gt;
        ///      &lt;rd:DataSourceID&gt;8ce6629b-9e37-49db-8795-81be03edf313&lt;/rd:DataSourceID&gt;
        ///      &lt;ConnectionProperties&gt;
        ///        &lt;DataProvider&gt;
        ///        &lt;/DataProvider&gt;
        ///        &lt;ConnectString&gt;
        ///        &lt;/ConnectString&gt;
        ///      &lt;/ConnectionProperties&gt;
        ///    [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Report2008Base {
            get {
                return ResourceManager.GetString("Report2008Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///             &lt;Textbox Name=&quot;RightBox_[:Name:]&quot;&gt;
        ///            &lt;Top&gt;[:TopCm:]cm&lt;/Top&gt;
        ///            &lt;Style&gt;
        ///              &lt;FontFamily&gt;gulim&lt;/FontFamily&gt;
        ///              &lt;TextAlign&gt;Right&lt;/TextAlign&gt;
        ///              &lt;PaddingLeft&gt;2pt&lt;/PaddingLeft&gt;
        ///              &lt;PaddingRight&gt;2pt&lt;/PaddingRight&gt;
        ///              &lt;PaddingTop&gt;2pt&lt;/PaddingTop&gt;
        ///              &lt;PaddingBottom&gt;2pt&lt;/PaddingBottom&gt;
        ///            &lt;/Style&gt;
        ///            &lt;ZIndex&gt;3&lt;/ZIndex&gt;
        ///            &lt;CanGrow&gt;true&lt;/CanGrow&gt;
        ///            &lt;Left&gt;0cm&lt;/Left&gt;
        ///          [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RightBox {
            get {
                return ResourceManager.GetString("RightBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;TableColumn&gt;
        ///            &lt;Width&gt;[:ColumnWidth:]cm&lt;/Width&gt;
        ///          &lt;/TableColumn&gt;
        ///		  과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TableColumn {
            get {
                return ResourceManager.GetString("TableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;TableRow&gt;
        ///              &lt;TableCells&gt;
        ///                [/ValueCells/]
        ///			  &lt;/TableCells&gt;
        ///              &lt;Height&gt;0.53333cm&lt;/Height&gt;
        ///            &lt;/TableRow&gt;
        ///			과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TableRow {
            get {
                return ResourceManager.GetString("TableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///             &lt;Textbox Name=&quot;TopBox_[:Name:]&quot;&gt;
        ///            &lt;Style&gt;
        ///              &lt;Color&gt;#1c3a70&lt;/Color&gt;
        ///              &lt;FontFamily&gt;gulim&lt;/FontFamily&gt;
        ///              &lt;FontSize&gt;18pt&lt;/FontSize&gt;
        ///              &lt;TextAlign&gt;Center&lt;/TextAlign&gt;
        ///              &lt;PaddingLeft&gt;2pt&lt;/PaddingLeft&gt;
        ///              &lt;PaddingRight&gt;2pt&lt;/PaddingRight&gt;
        ///              &lt;PaddingTop&gt;[:TopPt:]pt&lt;/PaddingTop&gt;
        ///              &lt;PaddingBottom&gt;2pt&lt;/PaddingBottom&gt;
        ///            &lt;/Style&gt;
        ///            &lt;ZIndex&gt;1&lt;/ZIndex&gt;
        ///            &lt;CanGrow&gt;true&lt;/[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TopBox {
            get {
                return ResourceManager.GetString("TopBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;TableCell&gt;
        ///                  &lt;ReportItems&gt;
        ///                    &lt;Textbox Name=&quot;ValueRow[:BoxName:]&quot;&gt;
        ///                      &lt;Style&gt;
        ///                        &lt;TextAlign&gt;[:TextAlign:]&lt;/TextAlign&gt;
        ///                        &lt;Color&gt;[:FontColor:]&lt;/Color&gt;
        ///                        &lt;BackgroundColor&gt;[:BackColor:]&lt;/BackgroundColor&gt;
        ///                        &lt;BorderColor&gt;
        ///                          &lt;Default&gt;DimGray&lt;/Default&gt;
        ///                        &lt;/BorderColor&gt;
        ///                        &lt;BorderStyle&gt;
        ///               [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ValueCell {
            get {
                return ResourceManager.GetString("ValueCell", resourceCulture);
            }
        }
    }
}
