//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReportTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;Chart Name=&quot;[:ChartName:]&quot;&gt;
        ///      &lt;ChartCategoryHierarchy&gt;
        ///        &lt;ChartMembers&gt;
        ///          &lt;ChartMember&gt;
        ///            &lt;Group Name=&quot;[:ChartName:]_CategoryGroup&quot;&gt;
        ///              &lt;GroupExpressions&gt;
        ///                &lt;GroupExpression&gt;=Fields!Name.Value&lt;/GroupExpression&gt;
        ///              &lt;/GroupExpressions&gt;
        ///            &lt;/Group&gt;
        ///            &lt;SortExpressions&gt;
        ///              &lt;SortExpression&gt;
        ///                &lt;Value&gt;=Fields!Name.Value&lt;/Value&gt;
        ///              &lt;/SortExpression&gt;
        ///            &lt;/SortExpressions&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;DataSet Name=&quot;[:DataSetName:]&quot;&gt;
        ///      &lt;Query&gt;
        ///        &lt;DataSourceName&gt;[:DataSourceName:]&lt;/DataSourceName&gt;
        ///        &lt;CommandText&gt;[:CommandText:]&lt;/CommandText&gt;
        ///      &lt;/Query&gt;
        ///      &lt;Fields&gt;
        ///        [/Fields/]
        ///      &lt;/Fields&gt;
        ///      &lt;rd:DataSetInfo&gt;
        ///        &lt;rd:DataSetName&gt;[:DataSetName:]&lt;/rd:DataSetName&gt;
        ///        &lt;rd:TableName&gt;[:TableName:]&lt;/rd:TableName&gt;
        ///        &lt;rd:TableAdapterName&gt;[:TableAdapterName:]&lt;/rd:TableAdapterName&gt;
        ///        &lt;rd:TableAdapterFillMethod&gt;
        ///        &lt;/rd:TableAdapterFillMeth [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataSet {
            get {
                return ResourceManager.GetString("DataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;DataSource Name=&quot;[:DataSourceName:]&quot;&gt;
        ///      &lt;ConnectionProperties&gt;
        ///        &lt;DataProvider&gt;
        ///        &lt;/DataProvider&gt;
        ///        &lt;ConnectString&gt;
        ///        &lt;/ConnectString&gt;
        ///      &lt;/ConnectionProperties&gt;
        ///      &lt;rd:DataSourceID&gt;58f5a201-08fe-49b5-92a4-9fe4cbb7534c&lt;/rd:DataSourceID&gt;
        ///    &lt;/DataSource&gt;.
        /// </summary>
        internal static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         &lt;Field Name=&quot;[:FieldName:]&quot;&gt;
        ///          &lt;DataField&gt;[:FieldName:]&lt;/DataField&gt;
        ///          &lt;rd:TypeName&gt;[:TypeName:]&lt;/rd:TypeName&gt;
        ///        &lt;/Field&gt;.
        /// </summary>
        internal static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                 &lt;TablixCell&gt;
        ///                  &lt;CellContents&gt;
        ///                    &lt;Textbox Name=&quot;[:FieldName:]&quot;&gt;
        ///                      &lt;CanGrow&gt;true&lt;/CanGrow&gt;
        ///                      &lt;KeepTogether&gt;true&lt;/KeepTogether&gt;
        ///                      &lt;Paragraphs&gt;
        ///                        &lt;Paragraph&gt;
        ///                          &lt;TextRuns&gt;
        ///                            &lt;TextRun&gt;
        ///                              &lt;Value&gt;=Fields![:FieldName:].Value&lt;/Value&gt;
        ///                              &lt;MarkupType&gt;HTML&lt;/MarkupType&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FieldCell {
            get {
                return ResourceManager.GetString("FieldCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                 &lt;TablixCell&gt;
        ///                  &lt;CellContents&gt;
        ///                    &lt;Textbox Name=&quot;Header_[:FieldText:]&quot;&gt;
        ///                      &lt;CanGrow&gt;true&lt;/CanGrow&gt;
        ///                      &lt;KeepTogether&gt;true&lt;/KeepTogether&gt;
        ///                      &lt;Paragraphs&gt;
        ///                        &lt;Paragraph&gt;
        ///                          &lt;TextRuns&gt;
        ///                            &lt;TextRun&gt;
        ///                              &lt;Value&gt;[:FieldText:]&lt;/Value&gt;
        ///                              &lt;Style&gt;
        ///                                &lt;Fon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HeaderCell {
            get {
                return ResourceManager.GetString("HeaderCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Report xmlns=&quot;http://schemas.microsoft.com/sqlserver/reporting/2008/01/reportdefinition&quot; xmlns:rd=&quot;http://schemas.microsoft.com/SQLServer/reporting/reportdesigner&quot;&gt;
        ///  &lt;Width&gt;[:TotalWidth:]cm&lt;/Width&gt;
        ///  &lt;Page&gt;
        ///    &lt;PageHeight&gt;[:PageHeight:]cm&lt;/PageHeight&gt;
        ///    &lt;PageWidth&gt;[:PageWidth:]cm&lt;/PageWidth&gt;
        ///    &lt;LeftMargin&gt;[:Margin:]cm&lt;/LeftMargin&gt;
        ///    &lt;RightMargin&gt;[:Margin:]cm&lt;/RightMargin&gt;
        ///    &lt;TopMargin&gt;[:Margin:]cm&lt;/TopMargin&gt;
        ///    &lt;BottomMargin&gt;[:Margin:]cm&lt;/BottomMa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Report2012 {
            get {
                return ResourceManager.GetString("Report2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Textbox Name=&quot;RightBox_[:Name:]&quot;&gt;
        ///  &lt;CanGrow&gt;true&lt;/CanGrow&gt;
        ///  &lt;KeepTogether&gt;true&lt;/KeepTogether&gt;
        ///  &lt;Paragraphs&gt;
        ///    &lt;Paragraph&gt;
        ///      &lt;TextRuns&gt;
        ///        &lt;TextRun&gt;
        ///          &lt;Value&gt;[:Value:]&lt;/Value&gt;
        ///          &lt;MarkupType&gt;HTML&lt;/MarkupType&gt;
        ///          &lt;Style&gt;
        ///            &lt;FontSize&gt;[:Font:]pt&lt;/FontSize&gt;
        ///            &lt;FontFamily&gt;gulim&lt;/FontFamily&gt;
        ///          &lt;/Style&gt;
        ///        &lt;/TextRun&gt;
        ///      &lt;/TextRuns&gt;
        ///      &lt;Style&gt;
        ///        &lt;TextAlign&gt;Right&lt;/TextAlign&gt;
        ///        &lt;LineHeight&gt;1pt&lt;/LineHeight&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RightBox {
            get {
                return ResourceManager.GetString("RightBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TablixColumn&gt;
        ///  &lt;Width&gt;[:ColumnWidth:]cm&lt;/Width&gt;
        ///&lt;/TablixColumn&gt;
        ///.
        /// </summary>
        internal static string TableColumn {
            get {
                return ResourceManager.GetString("TableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TablixMember /&gt;.
        /// </summary>
        internal static string TablelixMemberBase {
            get {
                return ResourceManager.GetString("TablelixMemberBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             &lt;TablixRow&gt;
        ///              &lt;Height&gt;[:RowHeight:]cm&lt;/Height&gt;
        ///              &lt;TablixCells&gt;
        ///                [/ValueCells/]
        ///              &lt;/TablixCells&gt;
        ///            &lt;/TablixRow&gt;
        ///.
        /// </summary>
        internal static string TableRow {
            get {
                return ResourceManager.GetString("TableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;Tablix Name=&quot;[:TableName:]&quot;&gt;
        ///        &lt;TablixBody&gt;
        ///          &lt;TablixColumns&gt;
        ///            [/TableColumns/]
        ///          &lt;/TablixColumns&gt;
        ///          &lt;TablixRows&gt;
        ///            &lt;TablixRow&gt;
        ///              &lt;Height&gt;[:HeaderHeight:]cm&lt;/Height&gt;
        ///              &lt;TablixCells&gt;
        ///                [/HeaderCells/]
        ///              &lt;/TablixCells&gt;
        ///            &lt;/TablixRow&gt;
        ///            [/TableRows/]
        ///          &lt;/TablixRows&gt;
        ///        &lt;/TablixBody&gt;
        ///        &lt;TablixColumnHierarchy&gt;
        ///          &lt;TablixMembers&gt;
        ///            [/C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tablix {
            get {
                return ResourceManager.GetString("Tablix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Tablix Name=&quot;Table1&quot;&gt;
        ///  &lt;TablixBody&gt;
        ///    &lt;TablixColumns&gt;
        ///      &lt;TablixColumn&gt;
        ///        &lt;Width&gt;2.55937cm&lt;/Width&gt;
        ///      &lt;/TablixColumn&gt;
        ///      &lt;TablixColumn&gt;
        ///        &lt;Width&gt;2.55937cm&lt;/Width&gt;
        ///      &lt;/TablixColumn&gt;
        ///    &lt;/TablixColumns&gt;
        ///    &lt;TablixRows&gt;
        ///      &lt;TablixRow&gt;
        ///        &lt;Height&gt;0.80215cm&lt;/Height&gt;
        ///        &lt;TablixCells&gt;
        ///          &lt;TablixCell&gt;
        ///            &lt;CellContents&gt;
        ///              &lt;Textbox Name=&quot;Textbox11&quot;&gt;
        ///                &lt;CanGrow&gt;true&lt;/CanGrow&gt;
        ///                &lt;KeepTogether&gt;true&lt;/Keep [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TitleItems {
            get {
                return ResourceManager.GetString("TitleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Textbox Name=&quot;TopBox_[:Name:]&quot;&gt;
        ///  &lt;CanGrow&gt;true&lt;/CanGrow&gt;
        ///  &lt;KeepTogether&gt;true&lt;/KeepTogether&gt;
        ///  &lt;Paragraphs&gt;
        ///    &lt;Paragraph&gt;
        ///      &lt;TextRuns&gt;
        ///        &lt;TextRun&gt;
        ///          &lt;Value&gt;[:Value:]&lt;/Value&gt;
        ///          &lt;MarkupType&gt;HTML&lt;/MarkupType&gt;
        ///          &lt;Style&gt;
        ///            &lt;FontSize&gt;[:Font:]pt&lt;/FontSize&gt;
        ///          &lt;/Style&gt;
        ///        &lt;/TextRun&gt;
        ///      &lt;/TextRuns&gt;
        ///      &lt;Style&gt;
        ///        &lt;TextAlign&gt;Center&lt;/TextAlign&gt;
        ///        &lt;LineHeight&gt;1pt&lt;/LineHeight&gt;
        ///      &lt;/Style&gt;
        ///    &lt;/Paragraph&gt;
        ///  &lt;/Paragraphs&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TopBox {
            get {
                return ResourceManager.GetString("TopBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                 &lt;TablixCell&gt;
        ///                  &lt;CellContents&gt;
        ///                    &lt;Textbox Name=&quot;ValueRow[:BoxName:]&quot;&gt;
        ///                      &lt;CanGrow&gt;false&lt;/CanGrow&gt;
        ///                      &lt;KeepTogether&gt;true&lt;/KeepTogether&gt;
        ///                      &lt;Paragraphs&gt;
        ///                        &lt;Paragraph&gt;
        ///                          &lt;TextRuns&gt;
        ///                            &lt;TextRun&gt;
        ///                              &lt;Value&gt;[:Value:]&lt;/Value&gt;
        ///                              &lt;MarkupType&gt;HTML&lt;/MarkupType&gt;
        ///                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValueCell {
            get {
                return ResourceManager.GetString("ValueCell", resourceCulture);
            }
        }
    }
}
